### ISSUE TITLE
Don't Escape Underscore in Links

### ISSUE THREAD

**Issue by dustinmichels** [executablebooks/mdformat#119]
**Describe the bug**

A standalone link with underscores in it was changed:

`"example.com/this_page_here"`

to

`"example.com/this\_page\_here"`

The link was standalone, eg not in the markdown format within parentheses.

- Python 3.7
- Mac

**Comment by hukkinj1** [comment]
Thanks for the issue! The escape here doesn't change rendered HTML in any way, so I'm tagging this as `enhancement`, not `bug`. I'll try to fix this soon regardless.

Underscores are a bit tricky to not escape, because if done carelessly, it's easy to introduce unwanted emphasis blocks. The heuristic I plan to use is:
- Escape an underscore always, unless
  - a) Both surrounding characters are NOT one of Unicode whitespace, start or end of line, or Unicode punctuation
  - b) Both surrounding characters are Unicode whitespace, or start or end of line

Your example would fall under category a) and be fixed by introducing this heuristic.

**Comment by dustinmichels** [comment]
Nice, thanks for responding.

The package is really cool and exactly what I was looking for.

I marked it as a bug because it does change/break the link in the underlying markdown, which feels a bit dangerous. But I see the rendered link it still fine so it's a bit of a grey area.
