### ISSUE TITLE
Document collapsing redundant backticks in backtick strings

### ISSUE THREAD

**Issue by jpmckinney** [executablebooks/mdformat#130]
For example:

```md
Test ```inline```
```

becomes:

```md
Test `inline`
```

Ideally, I'd prefer an option to maintain the original backticks.

https://github.com/executablebooks/mdformat/blob/master/STYLE.md

**Comment by hukkinj1** [comment]
Thanks for the issue, agree that this should and will be documented in STYLE.md :+1: 

When it comes to maintaining original backtick count, theres a few issues:
1. The syntax token stream we get from `markdown-it-py` does not contain (mostly) any style information. So technically this is a challenge.
2. I'm generally against making things configurable unless there's a very good reason. This is because __*a)*__ we can make almost anything configurable, I don't want the maintenance burden, and __*b)*__ an opinionated non-configurable formatter saves users from the need to argue which configuration to use.

In this case the default style (as few backticks as possible) is the most widely used and arguably the best style.

**Comment by jpmckinney** [comment]
Sure, this is just a documentation issue. I'll follow-up about backtick edge cases in https://github.com/executablebooks/MyST-Parser/issues/311
