### ISSUE TITLE
Consistent indentation levels

### ISSUE THREAD

**Issue by MikhailZex** [executablebooks/mdformat#162]
**Is your feature request related to a problem? Please describe.**

I use an extension called "All in one Markdown" on VSCode, one of its most useful features is the automatic generation of a ToC. ToC generation works just fine when a have lists that are 2 layers deep (list point with sub-points) but breaks for more than that (sub-sub-points)

**Describe the solution you'd like**

Consistent non-adaptive indentation with enjoy lines between list items.

```
- list level 1

     - list level 2
     
          - list level 3
```

**Describe alternatives you've considered**

Nothing reasonable

**Additional context**

This is the mdformat-gfm formatted file (I ended up writing the ToC manually): [file](https://github.com/spotDL/spotdlRedesign/blob/master/docs/docs/python.md)

**Comment by hukkinj1** [comment]
Hey, thanks for the issue!

I'm not exactly sure if I understand the problem. List indentation should consistent. Where/how did you experience an inconsistency? Can you give me an example Markdown where you don't like mdformat's formatting?

If this issue is about the empty lines between list items, then that should be consistent two. Tight lists don't have empty lines in between list items, and loose lists have an empty line between each and every list item.

If your ToC generator is somehow incompatible, you can have a look at the mdformat toc plugin and see if it works better https://github.com/hukkinj1/mdformat-toc

**Comment by MikhailZex** [comment]
I did a little more digging. The issue is with the VSC extension. your plugin is wayyy better. Thanks a lot.
