### ISSUE TITLE
Configurable fence character

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/mdformat#22]
Heya, is there a reason to use `~` over `` ` ``, which IMO is the more generally used character?
I feel this may put off general Markdown users 😬 
I think at least this should be configurable

https://github.com/executablebooks/mdformat/blob/39f40f6d829856ee1491c8c1ffb7d4fc30fc084b/mdformat/_renderer/token_renderers.py#L96

**Comment by hukkinj1** [comment]
Hey, this choice was made for practical reasons, because tildes allow syntax that backticks do not. See "Example 116" of the CommonMark spec https://spec.commonmark.org/0.29/#fenced-code-blocks
> Info strings for tilde code blocks can contain backticks and tildes

This is not true for backtick fences.

I personally prefer an opinionated formatter, and wouldn't want to make things configurable unless there is a good reason for one to use the opt-in style. Here tildes have one (admittedly small) advantage, so there is an argument to be made for using tildes instead of backticks.

I think we could however consider changing the default style to:
```
if info_string contains a backtick or tilde:
    use tildes
else:
    use backticks
```

What do you think?

**Comment by chrisjsewell** [comment]
> Info strings for tilde code blocks can contain backticks and tildes

Ah thats a weird quirk; you learn something new everyday lol

> What do you think?

Yeh that would be great cheers. It just looks a bit weird with `~`s when you are used to `` ` `` lol

**Comment by chrisjsewell** [comment]
Ta
