### ISSUE TITLE
Add option to disable lowercasing of Reference links

### ISSUE THREAD

**Issue by CCInc** [executablebooks/mdformat#273]
### Describe the problem

Some scripts that operate on MD files directly depend on the capitalization of the file contents. Right now, mdformat automatically lowercases reference link definitions, for example:

```
## [Unreleased]
[Unreleased]: https://github.com
```

mdformat would change to:

```
## [Unreleased]
[unreleased]: https://github.com
```

It would be nice to have an option to disable this lowercasing, so that doing text find/replaces within the file don't have to worry about capitalization.

### Steps to reproduce

somefile.MD
```
## [Unreleased]
[Unreleased]: https://github.com
```

run mdformat to get:

```
## [Unreleased]
[unreleased]: https://github.com
```

**Comment by hukkin** [comment]
Thanks for the issue!

I'm not sure I want this as link labels are case insensitive. Lower casing makes this obvious and the link labels consistent.

What would be your expected formatting for the following Markdown?
```markdown
[unreleased]

[Unreleased]

[Unreleased]: https://github.com
```

**Comment by CCInc** [comment]
In the case of running mdformat with the default settings, I would expect to lowercase them and keep the current behavior.

In the case of disabling case sensitivity, the formatter won't touch the casing, instead leaving it the same.

```
[unreleased]

[Unreleased]

[Unreleased]: https://github.com
```

I know with this setting, the formatter wouldn't be as opinionated; however, from a user perspective I would prefer the default behavior to be strongly opinionated, with the ability to disable certain rules. However, if this goes against the design philosophy of the library, I understand, and instead I can try to fix the offending scripts 😄

**Comment by hukkin** [comment]
Yeah, I do think it's probably better if you fix the offending scripts. If lowercasing link labels breaks your scripts, then I assume the mixed case example also does so, no matter how we format it. Fixing your scripts should be the more resilient solution.

**Comment by CCInc** [comment]
Understandable, my perspective is coming from adhering to specifications that define (perhaps improperly) how the file should be formatted. For example, my usecase was from https://keepachangelog.com/en/1.0.0, where the `[Unreleased]` tag is uppercased. In addition, the order of the link labels is intentional. My thoughts are, it would be nice to disable some features (link label ordering/capitalization) while maintaining formatting on the rest of the file, where mdformat can ensure a consistent styling.

**Comment by hukkin** [comment]
I see your point. But I don't currently feel like this is a strong enough case to justify adding configuration. I don't want to maintain a configurable formatter, but if you or anyone else wants to make a fork adding all sorts of switches, I think that'd actually be pretty great.

**Comment by ryan-williams** [comment]
[Example unwanted change](https://github.com/single-cell-data/TileDB-SOMA/pull/3740/commits/261eef614a830ff47fc022d77ce8b6295b0e1fce#diff-a22849c4105ede8562e7238e5e35431cf805c5d5c52707c385988297da816c7fR56) in my project:

```diff
-[`ExperimentAxisQuery`]: https://tiledbsoma.readthedocs.io/en/stable/python-tiledbsoma-experimentaxisquery.html
+[`experimentaxisquery`]: https://tiledbsoma.readthedocs.io/en/stable/python-tiledbsoma-experimentaxisquery.html
```

TIL that compliant parsers should apparently be fine with this, but I would prefer to leave it camel-cased; that is the proper name of the class, and the way it's always used.

"Default lower-case, with an escape-hatch" would be nice.

**Comment by jjmaestro** [comment]
+1 to, at least, having a escape hatch. I think that since the label casing shouldn't matter for the rendering, whatever the user chooses as the label should be respected and thus, left unchanged. If they picked a specific casing, it's for a reason.

If it's because of their render not being compliant, then changing the casing breaks things and forces them to fix the render which is not always possible. If it's because of "UX" (e.g. a user expects the class name to always have a certain casing), then changing the label in the links section breaks searching for the link label ("upstairs" is left unchanged, because that part is rendered as-is, so I would expect to have an exact, corresponding match "downstairs" so I can search for it).

I think all of this is avoided by just leaving the labels untouched. I understand that mdformat is an opinionated formatter but IMO, I can't see any upside in this case. I totally get sorting and deduping labels but that functionality still works leaving the labels unchanged.

@hukkin would you be open to reconsidering this? I would be happy to make a PR with the required changes. Thanks!!
