### ISSUE TITLE
Avoid replacing `---` with `___`

### ISSUE THREAD

**Issue by eggplants** [executablebooks/mdformat#328]
### Context

I would like to avoid replacing `---` with long `___`.

### Proposal

I suggest to add `--keep-hr` option to `mdformat`.

**Comment by hukkin** [comment]
Thanks for the issue!

The reasoning for the current thematic break style is explained in the docs: https://mdformat.readthedocs.io/en/stable/users/style.html#thematic-breaks

As mentioned in the [contributing docs](https://mdformat.readthedocs.io/en/stable/contributors/contributing.html#contributing), mdformat will only add configuration for a very good reason and use case. Do you have one?

**Comment by mar4th3** [comment]
Hi,
first thanks for this awesome tool. The rationale behind having this option is the use case of "markdown + pandoc".
With pandoc it is possible to specify a "preamble" section like [this one](https://pandoc.org/MANUAL.html#fonts) which uses thematic breaks. When these are converted to "70 character wide string of underscores" specifying these options in pandoc breaks.

**Comment by mar4th3** [comment]
Please ignore previous comment. After reading the pandoc [documentation](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block) it seems that the preamble can end with `...`. Maybe it is worth mentioning this in the doc?

**Comment by hukkin** [comment]
The Pandoc preamble you mention is also known as YAML frontmatter and mdformat supports it if you `pip install mdformat-frontmatter` (https://pypi.org/project/mdformat_frontmatter/).

**Comment by mar4th3** [comment]
Thank you! I should have read the [docs](https://mdformat.readthedocs.io/en/stable/users/plugins.html#id1) more carefully

**Comment by kdeldycke** [comment]
I would like to revisit this feature request, and have a way to specify the canonical form of a `<hr>` tag.

The default 70 character long `______________________________________________________________________` is fine to me. It is visually recognisable, and properly rendered by Markdown parsers of all flavours.

My problem is that I have to resort to multiple linters and formatters for some of my projects like [awesome-falsehood](https://github.com/kdeldycke/awesome-falsehood). In that case I both rely:
- on [`mdformat` to format my Markdown files](https://github.com/kdeldycke/workflows/blob/5c74485d9d27c8208f6afb2916d50f5c49971945/.github/workflows/autofix.yaml#L157-L163)
- on [`remark-lint`](https://github.com/remarkjs/remark-lint), to validate my content via [`awesome-lint`](https://github.com/sindresorhus/awesome-lint)

So `mdformat` is producing long `____(....)____` separators, while `remark-lint` is expecting the simpler `---`: https://github.com/kdeldycke/awesome-falsehood/actions/runs/5230012576/jobs/9443334318#step:3:13

This is because [`remark-lint`'s sub-plugin is expecting a normalized `---` rule](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-rule-style#presets).

Is it sensible to add a way to customize the canonical rule in `mdformat`?

**Comment by kdeldycke** [comment]
Good news everyone, there is a plugin for that! => https://github.com/csala/mdformat-simple-breaks 🥳
