### ISSUE TITLE
Option for formatting subitem-item spacing

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mdformat#385]
### Context

Currently the formatter would change
```
- item A
  - item A.a
- item B
```
as:
```
- item A

  - item A.a

- item B
```

### Proposal

Have an option to disable the spaces between item and subitems, i.e. format as the original:
```
- item A
  - item A.a
- item B
```

**Comment by hukkin** [comment]
Hey!

I can't reproduce your issue
```console
foo@bar:~$ pipx run mdformat --version
mdformat 0.7.17
foo@bar:~$ printf -- '- item A\n  - item A.a\n- item B' | pipx run mdformat -
- item A
  - item A.a
- item B
foo@bar:~$
```

I suspect the example list you provided is not complete, and that the complete list is in fact a ["loose list"](https://spec.commonmark.org/0.31.2/#loose) as a result of items you edited out. In that case mdformat will not make it a tight list, because it would change how it's rendered.
